arch: NestedUNet
batch_size: 20
dataset: IHCsmall_trainingset
deep_supervision: false
early_stopping: -1
epochs: 50
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 1000
input_w: 1000
load_pretrained_model: true
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: IHCsmall_trainingset_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 3
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
